name: MedievalEssentials
version: 1.4
author: DanTheTechMan
main: essentialsystem.Main
api-version: 1.13

commands:
  medievalessentials:
  fly:
  broadcast:
  motd:
  setmotd:
  seen:
  vanish:
  mute:
  unmute:
  nick:
  getpos:
  flyspeed:
  gm:
  logins:
  back:
  label: