name: MedievalEssentials
version: 1.1
author: KingdomProgrammers
main: essentialsystem.Main
api-version: 1.13

commands:
  medievalessentials:
  fly:
  broadcast:
  motd:
  setmotd:
  seen:
  vanish:
  mute:
  unmute:
  nick:
  getpos: