name: DansEssentials
version: '${project.version}'
author: Daniel Stephenson
main: dansplugins.dansessentials.DansEssentials
api-version: 1.13

commands:
  dansessentials:
  de:

permissions:
  de.help:
    default: true
  de.getpos:
    default: true
  de.usewarpsign:
    default: true
  de.back:
    default: op
  de.broadcast:
    default: op
  de.clearinv:
    default: op
  de.fly:
    default: op
  de.fly.others:
    default: op
  de.flyspeed:
    default: op
  de.gm:
    default: op
  de.gm.0:
    default: op
  de.gm.1:
    default: op
  de.gm.2:
    default: op
  de.invsee:
    default: op
  de.label:
    default: op
  de.mute:
    default: op
  de.unmute:
    default: op
  de.vanish:
    default: op
  de.placewarpsign:
    default: op