name: DansEssentials
version: 2.0-alpha-1
author: Daniel Stephenson
main: dansplugins.dansessentials.DansEssentials
api-version: 1.13

commands:
  dansessentials:
  fly:
  broadcast:
  motd:
  setmotd:
  seen:
  vanish:
  mute:
  unmute:
  nick:
  getpos:
  flyspeed:
  gm:
  logins:
  back:
  label:
  invsee:
  clearinv:

permissions:
  dansessentials.usewarpsign:
    default: true