name: MedievalEssentials
version: 1.5
author: DanTheTechMan
main: dansplugins.essentialsystem.MedievalEssentials
api-version: 1.13

commands:
  medievalessentials:
  fly:
  broadcast:
  motd:
  setmotd:
  seen:
  vanish:
  mute:
  unmute:
  nick:
  getpos:
  flyspeed:
  gm:
  logins:
  back:
  label:
  invsee:
  clearinv:
